### ISSUE TITLE
Package 'mkde' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Tracking#47]
Package [mkde](https://CRAN.R-project.org/package=mkde) is currently listed in CRAN Task View [Tracking](https://CRAN.R-project.org/view=Tracking) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by zeileis** [comment]
I wanted to check what the status here is. We had asked for a resolution within four weeks and three weeks already passed. Was there any contact with the maintainer or should the package be removed from the task view by the end of the week?

**Comment by basille** [comment]
Well summertime happened on my side. Aren't the devs already contacted by CRAN when a package is archived?

All 4 packages that are archived are rather old, with no update in the last 8 years at least. I doubt that the situation improves shortly, which is a pity… They don't have any public repo (such as GitHub) either, so there's no way to link it here. It's good to have this thread that summarizes the situation though!

**Comment by zeileis** [comment]
The maintainers are contacted, provided the e-mail address still works. (In some cases bouncing maintainer addresses have been the reason for the archival, though.)

However, it is not unusual (and completely understandable) that the maintainers are frustrated when this happens and do not feel compelled to follow up. So sometimes it helps if someone else sends an e-mail or creates a GitHub issue and asks if an update is planned - and potentially even offers help. Many reasons for archival on CRAN are not so hard to resolve.

It is up to you to judge what is the best way forward. I typically recommend to choose between:

- Contact the package authors (via e-mail or GitHub etc.), e.g., if the package was useful and/or seemed to be actively developed.
- Remove the packages immediately from the task view, e.g., because the package was not that useful in the first place and hadn't been updated for years.
- Wait some more (but not more than four weeks) before removing the package.

Of course, the decision what is "useful enough" to warrant more efforts is always somewhat subjective, but that's ok.

**Comment by basille** [comment]
Copy that. I find it uncomfortable to have an arbitrary estimation of usefulness though, and rather follow a common procedure for all packages. We'll discuss that with @rociojoo ASAP. Thanks for the suggestions @zeileis!

**Comment by zeileis** [comment]
We have been at this point before. Of course, it is desirable to be as objective as possible, but for the task views to be useful and to work, we will always have some level of subjectiveness involved. I wouldn't call this "arbitrary", though, it will be based on some objective criteria even if the decision cannot be made fully objectively.

As an example: In our Econometrics task we I had four packages archived that were all by the same author, all very small, all not updated since 2014/15, without active GitHub repository, and there were better packages on CRAN for the same tasks by now. Hence, I just removed those packages from the task view. I wouldn't call this an "arbitrary" decision. In most other cases I at least send an e-mail to the maintainer.

And in any case: The maintainers always have the option to resubmit their package to CRAN and to suggest reinclusion in the task view. So it's not like we're locking anyone out.

**Comment by basille** [comment]
Thanks @zeileis, this is useful feedback!

**Comment by basille** [comment]
Email sent to the maintainer on this day.
